
Imports Microsoft.Win32
Imports TWSClassLibrary
Imports TWSClassLibrary.SystemStatusManagement
Imports TWSClassLibrary.DatabaseManagement.TWSClassDatabaseManagement

Public MustInherit Class MClassConfigurationManagement


End Class
