'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace TerminalsWebService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://localhost/", ConfigurationName:="TerminalsWebService.TerminalsWebServiceSoap")>  _
    Public Interface TerminalsWebServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodSetNewSystemStatus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub WebMethodSetNewSystemStatus(ByVal AId As String, ByVal Status As TerminalsWebService.SystemStatus, ByVal TerminalId As Short, ByVal CommandValueData As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodGetNewSystemStatus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodGetNewSystemStatus(ByVal AId As String, ByRef TerminalIdToChangeStatuss As Short, ByRef CommandId As String, ByRef CommandValueData As String) As TerminalsWebService.SystemStatus
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/ACKSignalRecived", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub ACKSignalRecived(ByVal AId As String, ByVal TerminalId As Short, ByVal ACKSignall As TerminalsWebService.ACKSignal, ByVal Data As System.Data.DataSet, ByVal AckNoteString As String, ByVal LogSource As TerminalsWebService.LogSource, ByVal TDB As TerminalsWebService.Database, ByVal UserName As String, ByVal MethodName As String, ByVal SystemStatuss As TerminalsWebService.SystemStatus, ByVal SyncCounting As Byte)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodSyncTrucks", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodSyncTrucks(ByVal AId As String, ByVal TerminalID As Short, ByVal ClientNewTrucks As System.Data.DataSet) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodSyncAll", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub WebMethodSyncAll(ByVal AId As String, ByVal TerminalID As Short, ByVal ClientNewNobats As System.Data.DataSet, ByRef SyncNobats As System.Data.DataSet, ByRef SyncTrucks As System.Data.DataSet, ByRef SyncTerminals As System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodIdentifyTerminal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodIdentifyTerminal(ByVal AId As String, ByVal IdentifyCode As String) As Short
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodCreateNewterminal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub WebMethodCreateNewterminal(ByVal AId As String, ByVal TerminalName As String, ByRef TerminalId As Short, ByRef IdentifyCode As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodTerminalIdFromTerminalName", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodTerminalIdFromTerminalName(ByVal AId As String, ByVal TerminalName As String) As Short
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodLoggingReport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodLoggingReport(ByVal AId As String, ByVal DateAndTime As Date, ByRef Data As System.Data.DataSet) As Short
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodGetTruckTrace", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodGetTruckTrace(ByVal AId As String, ByVal Pelak As String, ByVal Serial As String, ByVal TotalRec As Short, ByRef Data As System.Data.DataSet) As TerminalsWebService.TruckTrace
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodGetLastNobatInOnlineifExist", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodGetLastNobatInOnlineifExist(ByVal AId As String, ByVal Pelak As String, ByVal Serial As String, ByVal TerminalID As Short, ByRef NobatDateTime As Date) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodCurrentShamsiDate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodCurrentShamsiDate() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodCurrentTime", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodCurrentTime() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodUserAuthentication", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WebMethodUserAuthentication(ByVal AId As String, ByVal UserId As String, ByVal UserPassword As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodDelNobatBarnameOnline", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub WebMethodDelNobatBarnameOnline(ByVal AId As String, ByVal TerminalID As Short, ByVal SyncTerminalID As Short, ByVal Pelak As String, ByVal Serial As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/WebMethodDelNobatUserRequest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub WebMethodDelNobatUserRequest(ByVal AId As String, ByVal TerminalID As Short, ByVal SyncTerminalID As Short, ByVal Pelak As String, ByVal Serial As String)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/")>  _
    Public Enum SystemStatus
        
        '''<remarks/>
        None
        
        '''<remarks/>
        SystemIdle
        
        '''<remarks/>
        SystemGeneral
        
        '''<remarks/>
        SystemClearNobatsTrucksBufferAndSilent
        
        '''<remarks/>
        SystemFullSilent
        
        '''<remarks/>
        WinServiceSilent
        
        '''<remarks/>
        StpExistNobatSilent
        
        '''<remarks/>
        ExecuteNonOutputSqlCommand
        
        '''<remarks/>
        ExecuteWithOutputSqlCommand
        
        '''<remarks/>
        SendCurrentStatus
        
        '''<remarks/>
        SetWinServiceTimerInterval
        
        '''<remarks/>
        SetWinServiceSyncCounting
        
        '''<remarks/>
        GetWinServiceConnectionString
        
        '''<remarks/>
        GetWinServiceTerminalId
        
        '''<remarks/>
        GetWinServiceDateTime
        
        '''<remarks/>
        GetWinServiceComputerInfo
        
        '''<remarks/>
        GetExistNobatsInOtherData
        
        '''<remarks/>
        GetSTPsTblConfigurationData
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/")>  _
    Public Enum ACKSignal
        
        '''<remarks/>
        NoneOrMsg
        
        '''<remarks/>
        AckError
        
        '''<remarks/>
        WebMethodSyncTrucks
        
        '''<remarks/>
        WebMethodSyncAll
        
        '''<remarks/>
        SystemStatusChangedToSystemGeneral
        
        '''<remarks/>
        SystemStatusChangedToSystemClearNobatsTrucksBufferAndSilent
        
        '''<remarks/>
        SystemStatusChangedToSystemFullSilent
        
        '''<remarks/>
        SystemStatusChangedToWinServiceSilent
        
        '''<remarks/>
        SystemStatusChangedToStpExistNobatSilent
        
        '''<remarks/>
        SystemStatusChangedToExecuteNonOutputSqlCommand
        
        '''<remarks/>
        SystemStatusChangedToExecuteWithOutputSqlCommand
        
        '''<remarks/>
        WinServiceStart
        
        '''<remarks/>
        WinServiceStop
        
        '''<remarks/>
        SendCurrentStatus
        
        '''<remarks/>
        SetWinServiceTimerInterval
        
        '''<remarks/>
        SetWinServiceSyncCounting
        
        '''<remarks/>
        GetWinServiceConnectionString
        
        '''<remarks/>
        GetWinServiceTerminalId
        
        '''<remarks/>
        GetWinServiceDateTime
        
        '''<remarks/>
        GetWinServiceComputerInfo
        
        '''<remarks/>
        GetExistNobatsInOtherData
        
        '''<remarks/>
        GetSTPsTblConfigurationData
        
        '''<remarks/>
        IdentifyTerminal
        
        '''<remarks/>
        ClientWinAppSettingSqlServerAdmin
        
        '''<remarks/>
        ClientWinAppServiceStart
        
        '''<remarks/>
        ServerWinServiceStart
        
        '''<remarks/>
        ServerWinServiceStop
        
        '''<remarks/>
        ServerWinServiceGarbageTimerElapsed
        
        '''<remarks/>
        ServerWinAppCreateTerminal
        
        '''<remarks/>
        ClientWinReportAppTimerStart
        
        '''<remarks/>
        ClientWinReportAppPassOk
        
        '''<remarks/>
        CenterControlChangeSystemStatus
        
        '''<remarks/>
        BarnamehOnLineDelNobat
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/")>  _
    Public Enum LogSource
        
        '''<remarks/>
        None
        
        '''<remarks/>
        ServerWinApplication
        
        '''<remarks/>
        ServerWinService
        
        '''<remarks/>
        ServerWebService
        
        '''<remarks/>
        ClientWinService
        
        '''<remarks/>
        ClientWinApplication
        
        '''<remarks/>
        ClientWebApplication
        
        '''<remarks/>
        ClientWinApplicationReporting
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/")>  _
    Public Enum Database
        
        '''<remarks/>
        None
        
        '''<remarks/>
        TDBClient
        
        '''<remarks/>
        TDBServer
        
        '''<remarks/>
        LocalSystem
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/")>  _
    Public Enum TruckTrace
        
        '''<remarks/>
        None
        
        '''<remarks/>
        NoPelakSerialFound
        
        '''<remarks/>
        NoRecordFound
        
        '''<remarks/>
        OK
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface TerminalsWebServiceSoapChannel
        Inherits TerminalsWebService.TerminalsWebServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TerminalsWebServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of TerminalsWebService.TerminalsWebServiceSoap)
        Implements TerminalsWebService.TerminalsWebServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub WebMethodSetNewSystemStatus(ByVal AId As String, ByVal Status As TerminalsWebService.SystemStatus, ByVal TerminalId As Short, ByVal CommandValueData As String) Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodSetNewSystemStatus
            MyBase.Channel.WebMethodSetNewSystemStatus(AId, Status, TerminalId, CommandValueData)
        End Sub
        
        Public Function WebMethodGetNewSystemStatus(ByVal AId As String, ByRef TerminalIdToChangeStatuss As Short, ByRef CommandId As String, ByRef CommandValueData As String) As TerminalsWebService.SystemStatus Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodGetNewSystemStatus
            Return MyBase.Channel.WebMethodGetNewSystemStatus(AId, TerminalIdToChangeStatuss, CommandId, CommandValueData)
        End Function
        
        Public Sub ACKSignalRecived(ByVal AId As String, ByVal TerminalId As Short, ByVal ACKSignall As TerminalsWebService.ACKSignal, ByVal Data As System.Data.DataSet, ByVal AckNoteString As String, ByVal LogSource As TerminalsWebService.LogSource, ByVal TDB As TerminalsWebService.Database, ByVal UserName As String, ByVal MethodName As String, ByVal SystemStatuss As TerminalsWebService.SystemStatus, ByVal SyncCounting As Byte) Implements TerminalsWebService.TerminalsWebServiceSoap.ACKSignalRecived
            MyBase.Channel.ACKSignalRecived(AId, TerminalId, ACKSignall, Data, AckNoteString, LogSource, TDB, UserName, MethodName, SystemStatuss, SyncCounting)
        End Sub
        
        Public Function WebMethodSyncTrucks(ByVal AId As String, ByVal TerminalID As Short, ByVal ClientNewTrucks As System.Data.DataSet) As System.Data.DataSet Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodSyncTrucks
            Return MyBase.Channel.WebMethodSyncTrucks(AId, TerminalID, ClientNewTrucks)
        End Function
        
        Public Sub WebMethodSyncAll(ByVal AId As String, ByVal TerminalID As Short, ByVal ClientNewNobats As System.Data.DataSet, ByRef SyncNobats As System.Data.DataSet, ByRef SyncTrucks As System.Data.DataSet, ByRef SyncTerminals As System.Data.DataSet) Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodSyncAll
            MyBase.Channel.WebMethodSyncAll(AId, TerminalID, ClientNewNobats, SyncNobats, SyncTrucks, SyncTerminals)
        End Sub
        
        Public Function WebMethodIdentifyTerminal(ByVal AId As String, ByVal IdentifyCode As String) As Short Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodIdentifyTerminal
            Return MyBase.Channel.WebMethodIdentifyTerminal(AId, IdentifyCode)
        End Function
        
        Public Sub WebMethodCreateNewterminal(ByVal AId As String, ByVal TerminalName As String, ByRef TerminalId As Short, ByRef IdentifyCode As String) Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodCreateNewterminal
            MyBase.Channel.WebMethodCreateNewterminal(AId, TerminalName, TerminalId, IdentifyCode)
        End Sub
        
        Public Function WebMethodTerminalIdFromTerminalName(ByVal AId As String, ByVal TerminalName As String) As Short Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodTerminalIdFromTerminalName
            Return MyBase.Channel.WebMethodTerminalIdFromTerminalName(AId, TerminalName)
        End Function
        
        Public Function WebMethodLoggingReport(ByVal AId As String, ByVal DateAndTime As Date, ByRef Data As System.Data.DataSet) As Short Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodLoggingReport
            Return MyBase.Channel.WebMethodLoggingReport(AId, DateAndTime, Data)
        End Function
        
        Public Function WebMethodGetTruckTrace(ByVal AId As String, ByVal Pelak As String, ByVal Serial As String, ByVal TotalRec As Short, ByRef Data As System.Data.DataSet) As TerminalsWebService.TruckTrace Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodGetTruckTrace
            Return MyBase.Channel.WebMethodGetTruckTrace(AId, Pelak, Serial, TotalRec, Data)
        End Function
        
        Public Function WebMethodGetLastNobatInOnlineifExist(ByVal AId As String, ByVal Pelak As String, ByVal Serial As String, ByVal TerminalID As Short, ByRef NobatDateTime As Date) As Boolean Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodGetLastNobatInOnlineifExist
            Return MyBase.Channel.WebMethodGetLastNobatInOnlineifExist(AId, Pelak, Serial, TerminalID, NobatDateTime)
        End Function
        
        Public Function WebMethodCurrentShamsiDate() As String Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodCurrentShamsiDate
            Return MyBase.Channel.WebMethodCurrentShamsiDate
        End Function
        
        Public Function WebMethodCurrentTime() As String Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodCurrentTime
            Return MyBase.Channel.WebMethodCurrentTime
        End Function
        
        Public Function WebMethodUserAuthentication(ByVal AId As String, ByVal UserId As String, ByVal UserPassword As String) As Boolean Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodUserAuthentication
            Return MyBase.Channel.WebMethodUserAuthentication(AId, UserId, UserPassword)
        End Function
        
        Public Sub WebMethodDelNobatBarnameOnline(ByVal AId As String, ByVal TerminalID As Short, ByVal SyncTerminalID As Short, ByVal Pelak As String, ByVal Serial As String) Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodDelNobatBarnameOnline
            MyBase.Channel.WebMethodDelNobatBarnameOnline(AId, TerminalID, SyncTerminalID, Pelak, Serial)
        End Sub
        
        Public Sub WebMethodDelNobatUserRequest(ByVal AId As String, ByVal TerminalID As Short, ByVal SyncTerminalID As Short, ByVal Pelak As String, ByVal Serial As String) Implements TerminalsWebService.TerminalsWebServiceSoap.WebMethodDelNobatUserRequest
            MyBase.Channel.WebMethodDelNobatUserRequest(AId, TerminalID, SyncTerminalID, Pelak, Serial)
        End Sub
    End Class
End Namespace
